### PR TITLE
Use explicit block when referenced in method

### LINKED ISSUE #753: [Stanford Arclight/prod] NameError: undefined local variable or method `block' for an instance of DeleteEadJob::IndexedEads
## Backtrace

    line 47 of [PROJECT_ROOT]/app/jobs/delete_ead_job.rb: each
    line 40 of [PROJECT_ROOT]/app/jobs/delete_ead_job.rb: all
    line 15 of [PROJECT_ROOT]/app/jobs/delete_ead_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/56667/faults/108515629)

### PR DESCRIPTION
**Pull request by corylown**
Fixes #753

### CODE REVIEW

**Review by marlo-longley — APPROVED** [review]

File: app/jobs/delete_ead_job.rb [hunk 1]
```diff
@@ -43,7 +43,7 @@ def all
     private
 
     # rubocop:disable Metrics/MethodLength
-    def each(&)
+    def each(&block)
       return enum_for(:each) unless block
```
Comment (jcoyne) [inline app/jobs/delete_ead_job.rb:47]: shouldn't this be `block_given?`

Comment (corylown) [reply app/jobs/delete_ead_job.rb:47]: It seems to work the same either way, but I think the better solution is https://github.com/sul-dlss/stanford-arclight/pull/756
